### ISSUE TITLE
Failed to installing the XPC helper manually 

### ISSUE THREAD

**Issue by yzpTsubasa** [kyleneideck/BackgroundMusic#107]
It couldn't been installed with `build_and_install.sh`, so that I tried the `MANUAL-INSTALL`.
But also failed, there is error when `Install the XPC helper`:

    `/Users/tsubasa/Documents/Projects/BackgroundMusic/BGMApp/BGMXPCHelper/main.m:61:31:
    error: 
          inferring '_Nonnull' for pointer type within array is deprecated
          [-Werror,-Wnullability-inferred-on-nested-type]
    int main(int argc, const char *argv[]) {
                                  ^
                                    _Nonnull 
    1 error generated.

    ** INSTALL FAILED **

    The following build commands failed:
      CompileC build/BGMApp.build/Release/BGMXPCHelper.build/Objects-normal/x86_64/main.o BGMXPCHelper/main.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    (1 failure)
    `

And my xcode version:
  `
  Xcode 8.3
  Build version 8E162
  `

**Comment by kyleneideck** [comment]
Thanks for reporting this. It looks like you’re running into this: http://lists.llvm.org/pipermail/cfe-commits/Week-of-Mon-20161107/176690.html

Can you try installing with `build_and_install.sh –w`? The `-w` option tells the install script to ignore compiler warnings, so that should let it finish installing.

I’ll try to actually fix the warning when I get a chance later today.

**Comment by yzpTsubasa** [comment]
Thanks a lot.😊
