### ISSUE TITLE
Issues when skype calling

### ISSUE THREAD

**Issue by crispycrisps** [kyleneideck/BackgroundMusic#112]
Volume does not change when attempting to adjust the volume for skype when skype calling. Is there something which I did wrong, or is volume-adjustment for skype calls not supported?

**Comment by kyleneideck** [comment]
I've just tried calling the Skype test contact and was able to change the volume of the incoming audio with Background Music. It's working for me with Skype 7.46 and 7.51 (the latest).

On the Audio/Video tab of Skype's preferences, do you have both output device options set to Background Music Device? There's also a volume slider on that tab, so that might be worth trying.

The only other thing I can think of is that maybe you're trying to adjust the input volume (your microphone), which isn't supported yet.

**Comment by brentonklassen** [comment]
Same issue, adjusting volume of Skype call is not working - OSX 10.12.6, Skype 8.10.0.4

**Comment by Ixxxp** [comment]
Same issue. Slider doesn't change sound at all. With "Background music" selected as input/output source (one-by-one or both).
Skype version 8.13.0.2
OSX 10.13.2

**Comment by xevidos** [comment]
I am running the following and still experiencing the issue.
Mac: 10.12.6
Skype: 8.24.0.2
BackgroundMusic: 0.1.1

After downgrading to Skype 7.59 it worked.

**Comment by kyleneideck** [comment]
Thanks for reporting this, everyone. It should be fixed in this snapshot release: https://github.com/kyleneideck/BackgroundMusic/releases/download/0.2.0-SNAPSHOT-1e5d625/BackgroundMusic-0.2.0-SNAPSHOT-1e5d625.pkg.

I've also opened #154, which would add a way to fix issues like this without having to edit the source code and rebuild.
