### ISSUE TITLE
Rename "Background Music Device" or add the ability for the user to do this

### ISSUE THREAD

**Issue by wolflambert** [kyleneideck/BackgroundMusic#116]
In the output devices menu, "Background Music Device" is just above the character limit and thus gets cut off.

![screen shot 2017-06-03 at 2 42 pm](https://cloud.githubusercontent.com/assets/4719242/26753640/fafa056e-486a-11e7-9b98-cb5e889a3a08.png)

This might seem like a minor thing, but it's quite annoying to me.

Better yet would be the ability for the end user to rename "Background Music Device" to whatever they please. I'd rename it to "Speakers", which would make the experience more seamless.

**Comment by kyleneideck** [comment]
Now that you mention it, that is pretty annoying. I think I probably never noticed before because I usually have another device underneath it that also has a long name. But in your screenshot it just looks like "device" is spelled wrong.

The simplest solution would be to just rename it from "Background Music Device" to "Background Music", so that would be my preference, at least for now.

I'll have to change some documentation before I push it, but I just tried changing `kDeviceName` in `BGMDriver/BGMDriver/BGM_Device.h` to "Background Music" and it seems to have worked fine. You could rename yours to "Speakers" the same way (change the constant and run `build_and_install.sh`) but then you'd have to make the same change whenever you update.

I'm not sure how much effort it would take to make it properly user-customisable, but I agree it would make things clearer when the name is shown in other apps' UIs and things like that. Or it might be better to rename it dynamically to include the real device's name -- "Headphones (Background Music)" or something like that.

That could be confusing if you want to use Background Music to record system audio, though. We might have to split BGMDevice into two devices, rather than one device with an input and an output stream, so they can have different names.

We might eventually move to having one virtual device for each real device so you can change devices with the normal menu and things like that. That would mean we'd have to rename the virtual device to include the real device's name anyway, but I think it's far enough away that renaming BGMDevice makes sense now.

**Comment by kyleneideck** [comment]
>I tried renaming it using an aggregate device in Audio MIDI Setup, but the tradeoff is that this disables volume control, which I'm not willing to sacrifice.

IIRC, Apple is (or was) working on adding controls to aggregate devices. I tried to use them for playthrough—forwarding the audio to the real output device—but ran into the same problem.
