### ISSUE TITLE
Microphoe not working

### ISSUE THREAD

**Issue by dnlxh** [kyleneideck/BackgroundMusic#120]
Hey, 

is it only me having problems with the microphone? When I'm using BackgroundMusic, my microphone won't work until I open the settings panel and click on my mic and leave it open. 

Anyone else got the problem?

**Comment by dnlx** [comment]
well it's definitely because of Backgroundmusic. After deinstalling it, it works fine again. I didn't change anything. It was working fine for 2-3 Month now. And now it's broken.

**Comment by kyleneideck** [comment]
Hi, thanks for the report. I'm not sure what would be causing this.

Is Background Music changing your default input device for some reason? It adds an input device (called "Background Music") but it shouldn't be set as your default input device unless you set it manually.

When you have Background Music open, does your mic stay selected in System Preferences > Sound > Input? Is its volume all the way up?

What program are you trying to use your microphone in? It might be trying to record from Background Music's input device for some reason.

Try recording from your microphone in QuickTime to see if that helps narrow down the problem. Go File > New Audio Recording, press the "V" next to the record button and make sure your mic is selected.

Also, what sort of microphone are you using?

**Comment by dnlx** [comment]
Hey,

thanks for answering. Noy BackGroundMusic ist not selecting my mic,
everything is normal. The problem just appeared. I'm  not using the
internal mic I'm using a "modmic 5". Recording with Quicktime doesn't work.
As well as Siri built in, I can't talk to her (I never use siri, but tested
it now)

Mit freundlichen Grüßen

Daniel Heeg

2017-07-23 9:15 GMT+02:00 Kyle Neideck <notifications@github.com>:

**Comment by kyleneideck** [comment]
I'm still not any closer to figuring this out, so I just have more questions I'm afraid.

>Recording with Quicktime doesn't work.

Does your mic appear in the list of input devices?

>my microphone won't work until I open the settings panel and click on my mic and leave it open.

By "settings panel" do you mean System Preferences > Sound > Input? Because if everything is normal there, that would mean your mic is already selected but you have to click it again for some reason.

Maybe your mic has both an input and an output device (from OS X's perspective). Is there any chance you actually had to select it in System Preferences > Sound > Output to get it to work?

>After deinstalling it, it works fine again.

Does it only start working again after you uninstall Background Music or does the same thing happen if you quit?

**Comment by dnlx** [comment]
Hey,

yes recording with quicktime doesn't work, because I can't speak, even if
my microphone is selected. It just don't work.
My Mic does appear in Input Devices, yes

Yes, by "my mic  won't work until i Open the settings panel.." i meant. I
have to open System Preferences -> Sound -> Input and click on my Mic  to
get it to work. If I close this windows tho. It will stops working, I have
to leave the Window open.

And it didn't matter, after closing Backgroundmusik it works fine. So I
think it's definitely because of Backgroundmusic, I didn't use
Backgroundmusic for 10 Days now and everything worked fine. I installed it
now to test ist again and it's still the same my mic only work if I leave
Sytem Preferences -> Sound -> output open and select my mic.

Mit freundlichen Grüßen

Daniel Heeg

2017-08-02 14:36 GMT+02:00 Kyle Neideck <notifications@github.com>:

**Comment by kyleneideck** [comment]
Is it `System Preferences -> Sound -> Input` or `System Preferences -> Sound -> Output` you have to select your mic in to get it to work? You said one but then said the other. It's important which because Background Music changes your system's default output device but not your system's default input device.

It might help if you attach some screenshots of both System Preferences tabs (Input and Output) with Background Music running.

It's very strange that you're able to select your microphone in QuickTime but still can't record. OS X shouldn't let Background Music break that even if it wanted to. Are you sure the volume of your microphone is turned up? There should be a separate "input volume" for your mic in `System Preferences -> Sound -> Input`.

It's also very strange that closing System Preferences stops your mic from working again. I have no idea why that would be happening.
