### ISSUE TITLE
Install issue on step 3

### ISSUE THREAD

**Issue by jbirdjan** [kyleneideck/BackgroundMusic#129]
Trying to install the app step three stops with a compilation error. After following the instructions listed for the workaround, the app fails to actually change any app volumes or balances, but still can change system volume. Hope this helps. Install log also attached.

`ERROR: Install failed at line 228 with the message:
A build command failed. Probably a compilation error.

Failed command:
                            sudo /usr/bin/xcodebuild -scheme Background Music -configuration Release -enableAddressSanitizer NO BUILD_DIR=./build RUN_CLANG_STATIC_ANALYZER=0 DSTROOT=/ clean install

Feel free to report this. If you do, you'll probably want to include the build_and_install.log file from this directory (/Users/Jjanney/Downloads/BackgroundMusic-master). But quickly skim through it first to check that it doesn't include any personal information. It shouldn't, but this is alpha software so you never know.

To try building and installing without this build script, see MANUAL-INSTALL.md.

You can also try ignoring compiler warnings with: build_and_install.sh -w

Error details:
Line 228. The last command was (probably)
    LAST_COMMAND="${BASH_COMMAND}" LAST_COMMAND_EXIT_STATUS=$?
which exited with status 0.
[build_and_install.log](https://github.com/kyleneideck/BackgroundMusic/files/1371048/build_and_install.log)
`

**Comment by kyleneideck** [comment]
From your build_and_install.log, it seems to be failing because of compiler warnings. Have you tried installing with `build_and_install.sh -w`?

I've added Xcode 9.0 and 9.1 to [.travis.yml](https://github.com/kyleneideck/BackgroundMusic/blob/master/.travis.yml), so the Travis build should start failing with the same error you're getting. I'm updating my Xcode to 9.0 and I'll fix the warnings when it's done.
