### ISSUE TITLE
wrong offset for memcpy in BGM_Device::ReadInputData and ::WriteOutputData ?

### ISSUE THREAD

**Issue by glaurent** [kyleneideck/BackgroundMusic#140]
I hesitate to do a pullrequest just for this, but, in BGM_Device::ReadInputData() :

```
memcpy(theDestination, mLoopbackRingBuffer + (theStartFrameOffset * 2), theNumberFramesToCopy1 * 8);
	if(theNumberFramesToCopy2 > 0)
	{
		memcpy(theDestination + (theNumberFramesToCopy1 * 2), mLoopbackRingBuffer, theNumberFramesToCopy2 * 8);
    }
```

Shouldn't the 2nd memcpy be

`memcpy(theDestination + (theNumberFramesToCopy1 * 8), ...)`

 ?

Similar issue in WriteOutputData()

**Comment by kyleneideck** [comment]
I think the second `memcpy` has `theNumberFramesToCopy1 * 2` instead of `theNumberFramesToCopy1 * 8` because the result is used for pointer arithmetic. `theDestination` is a `Float32 *`, so `theNumberFramesToCopy1 * 2` is implicitly multiplied by four. (It's multiplied by two first because there are two 32-bit samples per frame.) Does that make sense?

I wrote a test to check it and it seemed to be working: 7171cfcb78ba01b1a5c9c5ab68b236c37f374dfb

**Comment by glaurent** [comment]
Sorry but no, it doesn't. First, `theDestination` is the same in both `memcpy`, so your arithmetic should be identical. Second, `memcpy` copies the given number of bytes, regardless of the pointer type it's being passed (it's cast to `void*` anyway). There is no implicit multiplication.

**Comment by glaurent** [comment]
Yes you're correct, I was confused by the void* argument to memcpy and forgot that the addition on the pointer happens before memcpy() gets the argument. I think I also mixed with the Apple dev sample from which your code is inspired, and which uses a Byte* pointer while you use a Float32*.

**Comment by kyleneideck** [comment]
No worries. Judging by the debug code in those functions I probably had the same confusion at some point. Thanks all the same.
