### ISSUE TITLE
GDPMP app support

### ISSUE THREAD

**Issue by theLMGN** [kyleneideck/BackgroundMusic#161]
There are docs available here : https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/docs/PlaybackAPI_WebSocket.md

**Comment by kyleneideck** [comment]
I actually started on this a few months ago and got it mostly working. It's a bit complicated, though, because Background Music has to store the auth code it gets from GPMDP. Otherwise you'd have to type in a four-digit code from GPMDP every time you wanted to use it with Background Music.

I figured Background Music should probably store the permanent auth code in the keychain, which works, but apparently the process would be a bit smoother if Background Music was code-signed. So I might try looking into that when I get back to this task.

**Comment by subhead** [comment]
are there any news about GDPMP app support?

**Comment by kyleneideck** [comment]
GPMDP support should be working now as of https://github.com/kyleneideck/BackgroundMusic/releases/download/0.3.0-SNAPSHOT-04f1730/BackgroundMusic-0.3.0-SNAPSHOT-04f1730.pkg. It took a lot more code than any of the existing music players, so I wouldn't be surprised if there were bugs in it, but I haven't had any problems so far.
