### ISSUE TITLE
Add support for Decibel

### ISSUE THREAD

**Issue by matjolic** [kyleneideck/BackgroundMusic#17]
Would be very much appreciated :)
[http://sbooth.org/Decibel/](http://sbooth.org/Decibel/)

**Comment by hoke-t** [comment]
Implemented here: [https://github.com/hoke-t/BackgroundMusic/tree/Decibel](url)

Will submit pull request once #27 is accepted.

**Comment by kyleneideck** [comment]
Thanks, @hoke-t. I haven't tested https://github.com/hoke-t/BackgroundMusic/tree/Decibel yet, but I just read through it and it looks good to me. Just two minor things:

- When you moved the new files to `BGMApp/BGMApp/Music Players` you forgot to `git rm` the copies in `BGMApp/BGMApp`.
- Would it be better to link to https://sbooth.org/Decibel/ instead of http://sbooth.org/Decibel/ in the README? (If so, we should do the same for the link to VOX.)

**Comment by DotTheI** [comment]
Second this request

**Comment by hoke-t** [comment]
Working on it now.

**Comment by hoke-t** [comment]
Sorry the PR failed check, will fix it when I get a chance and resubmit.
