### ISSUE TITLE
Request: Change the volume sliders

### ISSUE THREAD

**Issue by setu4993** [kyleneideck/BackgroundMusic#174]
The current app-wise volume settings are counter-intuitive. Setting the app volume to 50% means no boost, reducing it means reducing volume, and increasing it means boosting the volume above system volume.

Instead I request switching the volume control to those similar to VLC (attached). Per app volume can be set to 0, bar at 100% of system volume, and a boost of +25%. It is a better visual design and more obvious.

<img width="86" alt="screenshot 2018-11-17 18 51 41" src="https://user-images.githubusercontent.com/1833708/48666962-01270e00-ea9a-11e8-8cff-32b63d5eeb0a.png">

**Comment by kyleneideck** [comment]
Agreed. I'm sure plenty of people have been surprised by clipping because of this. We should at least have some sort of visual indication that 50% is a special value for those sliders.

It can occasionally be useful to apply gain higher than +25%, so maybe we could add a new control to the extra controls section (i.e. the section shown when you click the "v" button for an app) to allow for that.

IIRC volume controls like VLC's are limited to something like +25% because setting it higher than that is likely to cause significant clipping. This currently true in Background Music, but we might be able to avoid it in most cases by raising the volume of the output device and lowering the volumes of every other app to offset that. If we manage that, we might want to revisit this issue, but I doubt that will be any time soon.

**Comment by setu4993** [comment]
Certainly. I know I was surprised when I first heard the clipping.

I'd still recommend using a similar to +25% gain. VLC allows for unto +100% gain, but the UI allows only for +25% (rest is through a keyboard shortcut). I think it should be similar, and assume that's what you were getting at with the 'v' button for each app.
