### ISSUE TITLE
Background Music won't launch after updating to 0.3.0

### ISSUE THREAD

**Issue by JohnnyMcL** [kyleneideck/BackgroundMusic#233]
I updated to Background Music 0.3.0 this morning and despite a supposedly successful installation, it does not appear to launch after opening and does not appear in my activity monitor. When opened, there is a momentary flicker in the menu bar as though its icon is shown for a split second, but it does not appear long enough to verify for sure whether that is the case. I have tried uninstalling and reinstalling, but the issue persists.

**Comment by kyleneideck** [comment]
Thanks for the report. My guess is that it's happening because I accidentally wiped out the entitlements for Background Music.app when I code signed 0.3.0, which it needs because Hardened Runtime is enabled now. I'm not sure why it seemed to work on my machine, but I've been able to reproduce a similar issue in a 10.14 VM.

I'll try to fix the code signing and release it as 0.3.1.

**Comment by kyleneideck** [comment]
@JohnnyMcL I've just released [v0.3.1](https://github.com/kyleneideck/BackgroundMusic/releases/tag/v0.3.1). Can you see if that solves the problem?

**Comment by muzimuzhi** [comment]
In macOS 10.14.6, v0.3.1 solves the problem.

**Comment by JohnnyMcL** [comment]
@kyleneideck That seems to have solved the problem, everything appears to be working as expected now. Thanks!
