### ISSUE TITLE
Volume controls are not working macOS 10.15.4

### ISSUE THREAD

**Issue by gmendel** [kyleneideck/BackgroundMusic#302]
I installed the latest stable version, and tried also with the latest snapshot 0.4.xx ... but the app specific app controls (firefox, chrome, Anesidora, WebX....) are not working... the master volume of this app is working.

Is there any specific action I need to drive on my mac. to get this to work?

**Comment by kyleneideck** [comment]
>Is there any specific action I need to drive on my mac. to get this to work?

No, it doesn't sound like you've done anything wrong. When you run Background Music, does it set your default audio device to one called "Background Music"?

Can you check in `System Preferences > Security and Privacy > Privacy` and make sure Background Music has permission to access microphones? (It doesn't actually access your microphone. It needs that permission because it uses a virtual input device, and macOS calls all input devices "microphones".)

With the latest snapshot version you can option-click on the Background Music icon (the one with the circles) to show a hidden menu option to enable debug logging. It's a bit limited at the moment, but it might help us figure out what's going on. You can get the logs by searching for "Background Music" in Console.app.

**Comment by tcarlsen** [comment]
I have same problem... cant volume control apps anymore. have checked privacy settings

**Comment by tcarlsen** [comment]
<img width="882" alt="Screenshot 2020-05-18 at 09 35 37" src="https://user-images.githubusercontent.com/145288/82186317-f21d5800-98ea-11ea-89ab-12d0cd17b4c1.png">
 logs says is changing volume. but it does not

**Comment by kyleneideck** [comment]
@tcarlsen Thanks, that helps narrow it down a bit. Is it just Twitch Desktop that isn't working for you or is it not able to control any apps? What version of Background Music do you have installed?

Also, can you check to make sure your default audio device gets set to "Background Music" when you run Background Music?

**Comment by tcarlsen** [comment]
I used 3.2 and no app worked.. I now upgraded to your latest snapshot pre release and only twitch aint working

**Comment by tcarlsen** [comment]
but its maily twitch im using it for :-)

**Comment by gmendel** [comment]
The microphone option (on the privacy area) what not showing b.music, but when I restarted my laptop, and started b.music, it was there ... when I enabled it for the Mic.  ... it started to work.

Thank you.

**Comment by tcarlsen** [comment]
@kyleneideck slack aint working for me either.. so my guess is that theres a problem with electron based apps

**Comment by tcarlsen** [comment]
I see you have a very old issue on franz app not working also electron based

https://github.com/kyleneideck/BackgroundMusic/issues/56

**Comment by chinarui-na** [comment]
@kyleneideck Any ideas about it. I also have problems that I can't control app volume which electron based.
