### ISSUE TITLE
Does not work for any apps on 10.15.5

### ISSUE THREAD

**Issue by danciu** [kyleneideck/BackgroundMusic#324]
The app does not work *at all* for apps on **10.15.5**.

I've tried using it **with** and **without** headphones.
**Output** -> External headphones;
**Output** -> MacBook Pro Speakers.

It's only the main volume slider that does work.

In comparison, the "Sound Control" app I'm trying now works flawlessly.

Info below, thanks.

**sw_vers:**
```
ProductName:	Mac OS X
ProductVersion:	10.15.5
BuildVersion:	19F101
```

**system_profiler SPAudioDataType:**
```
Audio:

    Devices:

        Background Music:

          Input Channels: 2
          Manufacturer: Background Music contributors
          Output Channels: 2
          Current SampleRate: 44100
          Transport: Virtual
          Input Source: Default
          Output Source: Default

        Background Music (UI Sounds):

          Input Channels: 2
          Manufacturer: Background Music contributors
          Output Channels: 2
          Current SampleRate: 44100
          Transport: Virtual
          Input Source: Default
          Output Source: Default

        External Headphones:

          Default Output Device: Yes
          Default System Output Device: Yes
          Manufacturer: Apple Inc.
          Output Channels: 2
          Current SampleRate: 44100
          Transport: Built-in
          Output Source: External Headphones

        MacBook Pro Microphone:

          Default Input Device: Yes
          Input Channels: 1
          Manufacturer: Apple Inc.
          Current SampleRate: 44100
          Transport: Built-in
          Input Source: MacBook Pro Microphone

        MacBook Pro Speakers:

          Manufacturer: Apple Inc.
          Output Channels: 2
          Current SampleRate: 44100
          Transport: Built-in
          Output Source: MacBook Pro Speakers

        Soundflower (2ch):

          Input Channels: 2
          Manufacturer: ma++ ingalls for Cycling '74
          Output Channels: 2
          Current SampleRate: 44100
          Transport: Unknown
          Input Source: Default
          Output Source: Default

        Soundflower (64ch):

          Input Channels: 64
          Manufacturer: ma++ ingalls for Cycling '74
          Output Channels: 64
          Current SampleRate: 44100
          Transport: Unknown
          Input Source: Default
          Output Source: Default

        Loopback Audio:

          Input Channels: 2
          Manufacturer: Rogue Amoeba Software, Inc.
          Current SampleRate: 44100
          Transport: Virtual
          Input Source: Default
```

**Comment by kyleneideck** [comment]
Can you install a snapshot build and [get some debug logs](https://github.com/kyleneideck/BackgroundMusic/wiki/Getting-Debug-Logs)? I'm on 10.15.6 at the moment, but I would have tested it on 10.15.5 at some point, so it might else to do with your system. Your hardware looks like it would be more or less the same as mine.

It's also worth checking that your system output device gets set to the Background Music device when you open the app. And check in System Preferences that Background Music has permission to access microphones. (It needs that because the driver publishes a virtual input device to send out the system audio.)

**Comment by danciu** [comment]
Hello @kyleneideck, it does work when I manually change the output to Background Music, however, the app does not set that by itself, and I had no idea that needs to be done. My apologies. In comparison, Sound Control does not add an output device for this behaviour to work. All good though, I will use it as such, many thanks for maintaining this and making it available to the world. All the best!

**Comment by danciu** [comment]
@kyleneideck, one question if I may, just to know if this is a bug: selecting 100% on both sliders (Main slider and App slider) distorts the sound terribly and I reckon it amplifies the sound output - is this a bug, or 0db on the slider is actually in the middle, not at 100%?

**Comment by kyleneideck** [comment]
Yeah, the middle of the slider is 0 dB. I like to have the option to go above that because sometimes an app is too quiet even at its full volume and you can usually tell when it's unlikely to cause clipping. I definitely agree that it's bad UI, though. I'm pretty sure it confuses more people than it helps.

There's a note about it in the README (https://github.com/kyleneideck/BackgroundMusic#known-issues-and-solutions), but I'd like to get a real solution working at some point. I've been thinking about trying to have it raise the overall volume when you set an app's volume above 0 dB and offset every other app so that their volumes don't actually change. It's a bit complicated, though, because I don't know if there's a way to figure out what that offset should be, short of some sort of calibration process.

**Comment by danciu** [comment]
Hi,

I think the overall UI is pretty good.
In regards to the above, I think there are various quick UI changes that would make that more apparent (I've included a quick mock below).
A great feature would include pulling and short 'locking' on the slider as it approaches one of the lines - or even just for the middle one representing 0db.

![mbg](https://user-images.githubusercontent.com/2565702/85750320-80160b00-b701-11ea-970c-f6036a59da15.png)

Cheers
