### ISSUE TITLE
Request: Indicate which application is generating audio

### ISSUE THREAD

**Issue by carlosedp** [kyleneideck/BackgroundMusic#342]
I'd like to know if it's possible to have some visualization to the menu items if the application is generating audio (like a LED) or some kind of meter showing the audio per app.

Also with this it might be great to have a setting to filter and show only the apps that are generating audio.

Thanks for the great application!

**Comment by kyleneideck** [comment]
BGMDriver (the virtual audio driver) gets a list of the 'clients' that have registered with CoreAudio to play audio. It also gets a bundle ID and PID for each client.

BGMDriver knows whether a client is playing audio or not, so it could send the list of clients currently playing audio to BGMApp (`Background Music.app`). Then BGMApp could try to match the clients to the apps and light up the LEDs for those apps.

I think it actually might even be better not to worry about whether an app is playing or has played audio and just indicate/filter the apps that have a client registered with CoreAudio. In my experience, there usually aren't that many.

BGMApp wouldn't always be able to figure out which app is actually playing the audio from the user's perspective, since it has to go by the processes that it matches to the clients' bundle IDs and PIDs. That's also the main reason that the app volume controls don't work for some apps.

Even with that limitation, I agree that it would definitely help you figure out which volume sliders will actually do anything.

My preference is probably to move apps into a different part of the UI in BGMApp when they match with a CoreAudio client. Maybe we could just put them at the top of the list.

We might also want to consider moving apps from the More Apps menu to the main menu when they match with a client.
