### ISSUE TITLE
Does not work on Zoom

### ISSUE THREAD

**Issue by aathmakuri034** [kyleneideck/BackgroundMusic#431]
I was trying to use this on zoom but it seems that it does not work. Sounds robotic

**Comment by pievalentin** [comment]
Probably your internet connection is faulty

**Comment by aathmakuri034** [comment]
The audio was working fine before I tried to switch to the background music option. I thought that might have been the case so I ran a speed test. Download speed was good. Not bad enough to make the voice seem robotic
<img width="573" alt="Screen Shot 2021-02-08 at 1 00 58 PM" src="https://user-images.githubusercontent.com/67123941/107268705-28b57880-6a0e-11eb-91b4-dac7d48d6a4e.png">

**Comment by ZB2045** [comment]
I had the same exact problem. Can't figure out a way around it though.

**Comment by thecoolwinter** [comment]
Actually I've figured it out, if you open zoom after installing BackgroundMusic, go to `Audio Settings` in the bottom left and select the `Background Music` output. This will route the zoom audio through BackgroundMusic instead of around it and straight to an output device.

<img width="496" alt="Screen Shot 2021-03-10 at 11 59 44 AM" src="https://user-images.githubusercontent.com/35942988/110675200-3fc7c180-8198-11eb-8d7d-b6a93af0f847.png">

**Comment by ZB2045** [comment]
Thanks "thecoolwinter" it works now! Thats what I tried before and it wasn't working but now it works so I guess something was fixed.

**Comment by ConorMacLean** [comment]
> Actually I've figured it out, if you open zoom after installing BackgroundMusic, go to `Audio Settings` in the bottom left and select the `Background Music` output. This will route the zoom audio through BackgroundMusic instead of around it and straight to an output device.
> 
> <img alt="Screen Shot 2021-03-10 at 11 59 44 AM" width="496" src="https://user-images.githubusercontent.com/35942988/110675200-3fc7c180-8198-11eb-8d7d-b6a93af0f847.png">

this is exactly what i was looking for thank you!
