### ISSUE TITLE
build_and_install.sh fails at the CompileAssetCatalog step

### ISSUE THREAD

**Issue by YushoSanogawa** [kyleneideck/BackgroundMusic#436]
[build_and_install.log](https://github.com/kyleneideck/BackgroundMusic/files/5993513/build_and_install.log)

Sorry, again.

I got a below message, when I run "./build_and_install.sh -w".
How can I solve this?

""""
ERROR: Install failed at line 233 with the message:
A build command failed. Probably a compilation error.

Feel free to report this. If you do, you'll probably want to include the build_and_install.log file from this directory (/Users/(myhostname)/BackgroundMusic). But quickly skim through it first to check that it doesn't include any personal information. It shouldn't, but this is alpha software so you never know.

To try building and installing without this build script, see MANUAL-INSTALL.md.

You can also try ignoring compiler warnings with: ./build_and_install.sh -w

Error details:
Line 233. The last command was (probably)
sudo /usr/bin/xcodebuild -scheme Background Music -configuration Release -enableAddressSanitizer NO BUILD_DIR=./build RUN_CLANG_STATIC_ANALYZER=0 DSTROOT=/ OTHER_CFLAGS="-Wno-error" install
which exited with status 65.
""""

**Comment by kyleneideck** [comment]
I found someone who got a similar error because they had never launched the copy of Xcode they were using: https://xamarin.github.io/bugzilla-archives/59/59709/bug.html

It could also be that you don't have the Xcode Command Line Tools installed. I think Xcode should install them when you open it for the first time.

If that doesn't fix the problem, can you try installing the latest release to see if that works? https://github.com/kyleneideck/BackgroundMusic/releases/tag/0.4.0-SNAPSHOT-c0ab98b

**Comment by YushoSanogawa** [comment]
As "https://xamarin.github.io/bugzilla-archives/59/59709/bug.html" says, I once ran Xcode, I could install Backgroud Music app. 
Thank you kindly for your quick and competent response.
