### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by turrball** [kyleneideck/BackgroundMusic#44]
Not an 'issue' per se, but I just signed up on GitHub to drop in and say a big thank you for making this. Running without any hindrance on my MacBook Pro (Late 2013) with OS X 10.11.4 El Capitan. 

Incredibly useful. It should be an inbuilt feature in OS X and won't be surprised if Apple 'adopts' the idea as a part of the OS in the future. I'll be glad to support you with system tests and bug reports through the development. 😊

Best,
T.

**Comment by kyleneideck** [comment]
Thanks, that's really good to hear. And yeah, I agree it'd be pretty great if Apple [Sherlocked](https://www.urbandictionary.com/define.php?term=sherlocked&defid=5195210) some of these ideas. Especially since they'd be able to make changes to Core Audio so their version could be much faster/lower latency.
