### ISSUE TITLE
Unable to delete virtual device in mac

### ISSUE THREAD

**Issue by southsea3026** [kyleneideck/BackgroundMusic#606]
> There's no template for this issue type. I just wanted to make it clear that it's OK to submit other types of issues.

I download and delete app few month ago and still not know how to fully delete BackgroundMusic.
As see the screenshots theres a device which 'Background Music'.
Help me to delete virtual device...
(I delete BackgroundMusic app as instruction.)

![Screen Shot 2022-06-22 at 5 12 59 PM](https://user-images.githubusercontent.com/86471807/174978985-09569e2a-fa24-4fb0-a3fe-3d763aba84ac.png)
![Screen Shot 2022-06-22 at 5 13 47 PM](https://user-images.githubusercontent.com/86471807/174978998-442d0f7f-f61b-45b8-a208-c47357e36c40.png)
![Screen Shot 2022-06-22 at 5 13 39 PM](https://user-images.githubusercontent.com/86471807/174979005-8f04d1ae-e187-4d06-bd70-5be068b143e2.png)

**Comment by kyleneideck** [comment]
There's no way to automatically remove the device when you delete `Background Music.app`, unfortunately.

You need to follow these instructions: <https://github.com/kyleneideck/BackgroundMusic#uninstall>. Since you've already deleted `Background Music.app`, you'll need to download the project (a .zip file) to get the uninstaller. That's explained in the instructions.

If that doesn't work for you, restart your computer. If it still hasn't worked after that, let me know and I'll reopen this issue.

**Comment by southsea3026** [comment]
clear complete as sun
thx :)
