### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by jcampbell05** [kyleneideck/BackgroundMusic#66]
I would love a high level explanation :)

**Comment by kyleneideck** [comment]
The two main parts are an audio driver, BGMDriver, and the program that controls the driver, BGMApp. BGMDriver adds a virtual audio device to your system, which I call BGMDevice. 

From the user's perspective, BGMDevice appears as one input device and one output device, both named "Background Music Device". They're shown in System Preferences > Sound along with the real audio devices.

When you start BGMApp, it sets BGMDevice as your system's default output device so the system (i.e. Core Audio) will start sending all[1] your audio data to BGMDriver. BGMDriver plays that audio on BGMDevice's input stream, and the user can record it by selecting "Background Music Device" in QuickTime the same way they'd select a microphone.

So that you can still hear the audio, BGMApp starts listening to BGMDevice's input stream and playing the audio out of your real output device. (See [BGMPlayThrough](https://github.com/kyleneideck/BackgroundMusic/blob/master/BGMApp/BGMApp/BGMPlayThrough.h)). 

There are a few programs that work the same way, but, for various technical reasons, I only ended up using code from Apple's [Core Audio User-Space Driver Examples](https://developer.apple.com/library/mac/samplecode/AudioDriverExamples/Introduction/Intro.html).

The auto-pausing and per-app volume features rely on the fact that BGMDriver can also see the audio from each program (technically each "client") before Core Audio mixes it all together. When you change an app's volume, BGMApp sends the new volume to BGMDriver, which applies the app volumes by modifying the apps' audio data directly.

To know when to pause your music player, first BGMApp tells BGMDriver which program you've set as your music player. Then it listens for BGMDriver to tell it when a different program starts playing audio. It checks if your music player is playing music, and pauses it if it is. When the other program stops playing audio, BGMDriver tells BGMApp and BGMApp unpauses your music.

Let me know if you have any more questions or if any of this is unclear. [DEVELOPING.md](https://github.com/kyleneideck/BackgroundMusic/blob/master/DEVELOPING.md) might also be useful. Actually, I might add this post to DEVELOPING.md as a summary.

[1] All, unless you're playing audio through a program that's set to always use a specific device, or one that doesn't switch to the new default device right away. The latter would usually be a bug in that program and I doubt we could do anything about it.

**Comment by jcampbell05** [comment]
This is great it cleared up a few technical aspects which I couldn't gather from the code or the DEVELOPING.md, specifically how you mixed the audio together.
