### ISSUE TITLE
Volume change beep

### ISSUE THREAD

**Issue by Ivoah** [kyleneideck/BackgroundMusic#7]
With BackgroundMusic running, the volume change beep gets cut off sometimes. OS X 10.11.4

**Comment by cHoco** [comment]
I'm not sure if we are experiencing the same issue, but in my case with BackgroundMusic as output device the feedback sound of volume change is completely different than without it, like it's popping, higher than it could handle.

**Comment by ZV95** [comment]
I'm going to bring this back up, and say that I can reproduce this issue. At some times when the volume buttons are used they will produce what seems like a third or half of their intended sound but then break up. Not sure why, but I can reproduce this.

**Comment by cHoco** [comment]
The fix for https://github.com/kyleneideck/BackgroundMusic/issues/46 seems to have fixed this as well!

**Comment by TitanNano** [comment]
I'm also experiencing this, it's sounds very different.

**Comment by kyleneideck** [comment]
I'm not sure whether I never actually fixed this properly or CoreAudio changed and reintroduced it, but I'm pretty sure I've fixed it now.

The fix for #46 was to avoid making calls to the HAL from BGMApp during BGM_Device::StartIO because they were causing deadlocks. The fix for this I just committed adds a few of those calls back, so it might reintroduce #46 to some extent.

I haven't had any problems with it, but I've only tested it on macOS 10.12. So let me know if you get any lockups or anything like that. Or if this doesn't actually fix the sounds getting cut off.
