### ISSUE TITLE
Can't compile APP

### ISSUE THREAD

**Issue by hellvesper** [kyleneideck/BackgroundMusic#70]
I've got an error:

> sudo /usr/bin/xcodebuild -project BGMApp/BGMApp.xcodeproj -target Background Music -configuration Release RUN_CLANG_STATIC_ANALYZER=0 DSTROOT=/ clean install
Build settings from command line:
    DSTROOT = /
    RUN_CLANG_STATIC_ANALYZER = 0

>xcodebuild: error: Unknown build action 'Music'.

Then i launch build command manual
>`sudo /usr/bin/xcodebuild -project BGMApp/BGMApp.xcodeproj -target Background\ Music -configuration Release RUN_CLANG_STATIC_ANALYZER=0 DSTROOT=/ clean install` 
and got another error:
`** INSTALL FAILED **

>The following build commands failed:
	CompileC build/BGMApp.build/Release/Background\ Music.build/Objects-normal/x86_64/BGMAppVolumes.o BGMApp/BGMAppVolumes.mm normal x86_64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

My system is: macOS Sierra 10.12 (16A294a) with Xcode 8.0

[build_and_install.log.txt](https://github.com/kyleneideck/BackgroundMusic/files/423300/build_and_install.log.txt)

**Comment by kyleneideck** [comment]
Hi, thanks for reporting this. I haven't tried building on Sierra or with Xcode 8 yet. I'm downloading them now.

In the meantime, from your logs it looks like your build might only be failing because warnings-as-errors is on. Try building with `-Wno-error`:

`/usr/bin/xcodebuild -project BGMApp/BGMApp.xcodeproj -target Background\ Music -configuration Release RUN_CLANG_STATIC_ANALYZER=0 DSTROOT=/ OTHER_CFLAGS="-Wno-error" clean install`

**Comment by hellvesper** [comment]
Thanks a lot! With that flag all compiled successfully.
