### ISSUE TITLE
Sandbox needs to be extended

### ISSUE THREAD

**Issue by Qix-** [kyleneideck/BackgroundMusic#72]
Hey Kyle,

I realize I just commented over on your SO answer about this, but at that point I figured it was only specific to my own project.

I'm trying to implement an AudioServerPlugin (HAL) of my own but I'm running into that pesky error:

> Sep  2 03:55:28 junon-C02R52QSG8WM com.apple.audio.DriverHelper[98264]: The plug-in named CaptainJack.driver requires extending the sandbox for the mach service named me.junon.CaptainJack.

I cloned/built/installed Background Music and it appeared to work the first time just fine. I went to see if it was merely that the XPC helper's executable lived inside an app bundle (well, an .xpc bundle - is there anything special about that suffix?) by moving the XPC process into `/tmp` and `chown`-ing it to root:weel and modifying the launchd plist to point to it.

If it worked, then I could have asserted that the executable could live anywhere. Needless to say it didn't work, and then both my own project as well as Background Music was giving me the sandbox extension error again.

So I went to revert my changes. Restarted coreaudiod, I even restarted my computer - still getting the error.

Ran uninstall.sh and then build_and_install.sh again; same thing.

Just like with my project, the device shows up correctly and I can switch to it, but `com.apple.audio.DriverHelper` (completely ironic name, I'm sure) spits out that sandbox extension error and refuses to let XPC connect.

I saw your stackoverflow answer, and I'm certain all of my plist files are right and permissions/ownership sorted, but it still refuses to allow me to connect.

I feel like this is something simple that I'm missing. I know it's not an actual XPC call that's causing it as stripping out all of the XPC code and just having the 'husk' of a service yields the same result.

Advice? :P

---

EDIT: welp, tried it again, and now Background Music's audio devices are working, though Console is still showing the expansion message. Is it innocuous? If that's the case, then something _is_ wrong with my XPC code.

I've been pulling my hair out for hours >.>

**Comment by kyleneideck** [comment]
>well, an .xpc bundle - is there anything special about that suffix?

I wouldn't think so. The Mach services Apple uses in it's HAL plug-ins, like AirPlayXPCHelper and bluetoothaudiod, aren't in bundles at all.

>Is it innocuous?

I'm pretty sure it is, yeah. I get it for the Apple HAL plug-ins as well (AirPlay.driver, etc.). But Background Music should still work even if it can't connect through XPC. The only thing we use XPC for at the moment is to synchronize the HAL plug-in (BGMDriver) with the app that plays the audio through to the real device (BGMApp) when audio starts playing. So we don't have to leave IO running all the time, which uses CPU, or drop frames, BGMDriver waits until BGMApp tells it through XPC that the real device is ready. See [BGMDriver/BGM_Device.cpp#L1861](https://github.com/kyleneideck/BackgroundMusic/blob/master/BGMDriver/BGMDriver/BGM_Device.cpp#L1861) and [BGMApp/BGMPlayThrough.cpp#L263](https://github.com/kyleneideck/BackgroundMusic/blob/master/BGMApp/BGMApp/BGMPlayThrough.cpp#L263).

The easiest way to confirm that it's actually working is probably to install a debug build (`build_and_install.sh -d`) and look for "BGM_Device::StartIO: Ready for IO" in your syslog. I think you could also check by copying the logging stuff from [com.bearisdriving.BGM.XPCHelper.plist.template#L39](https://github.com/kyleneideck/BackgroundMusic/blob/master/BGMApp/BGMXPCHelper/com.bearisdriving.BGM.XPCHelper.plist.template#L39) into your `/Library/LaunchDaemons/com.bearisdriving.BGM.XPCHelper.plist` and restarting `coreaudiod`. Or you could just play a short sound and listen for dropped frames at the start.

I just tried with a debug build on 10.12 and according to the logs it works fine. I also made sure it installed BGMXPCHelper to `/Library/Application Support/Background Music` instead of `/usr/local/libexec` in case there were some new restrictions on the executable's location.

Are you able to connect to other Mach services in the root bootstrap namespace from your driver? I used the snippet below to test that. You can easily tell if it sent the XPC message successfully because it'll crash your `AirPlayXPCHelper` process.

```
    xpc_connection_t connection = xpc_connection_create_mach_service("com.apple.AirPlayXPCHelper", NULL, 0);
    if (connection)  {
        printf("Got a connection\n");
        xpc_connection_set_event_handler(connection, ^(xpc_object_t event) {
            printf("Client event handler\n");
            if (event) {
                char* eventDesc = xpc_copy_description(event);
                if (eventDesc) {
                    printf("Event: %s\n", eventDesc);
                }
            }
        });
        xpc_connection_resume(connection);
        xpc_connection_send_message(connection, xpc_dictionary_create(NULL, NULL, 0));
    }
    for (;;) {
        CFRunLoopRunInMode(kCFRunLoopDefaultMode, DBL_MAX, TRUE);
    }
```

Does `launchctl print system/name.of.your.mach.service` find your service? If not, I think that would mean your service isn't in the root/global namespace.

**Comment by Qix-** [comment]
Just want to come back and close this + say thanks; your example made something apparent; our use cases for an audio server plugin are different, and XPC is really not suited for this task in my case haha. I realized you only used it for synchronization, and what's more is that you just loopback the output to the input (genius, btw. Had a rather significant 'a ha' moment when I realized what the loopback ring buffer was for).

I went and looked in `AudioServerPlugIn.h` and found out that with a proper Plist entry you can enable network operations. It appears to be the only other form of IPC allowable inside the sandbox, and the only one that doesn't require any sort of main loop.

I needed to stream audio in and out of the plugin itself, all in user-space. The socket juggling is a little clunky at the moment but (amazingly) it works.

Thank you again :)
